server:
  port: 8081

spring:
  application:
    name: customer-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: customer-service
      authentication-database: admin
logging:
  level:
    org.springframework: INFO
    com.bank.customer: DEBUG
